### ISSUE TITLE
Document CLITool

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/kolasu#115]
Explain how it can be used. Also consider permitting to instantiate the parser reflectively

**Comment by loradd** [comment]
I think the documentation should also include an example illustrating how the single commands can be included as subcommands in a project-specific cli tool:

```kotlin
class ExampleCommand: CliktCommand(
    name = "example-cli"
) {
    init {
        subcommands(
            AnotherCommand(),  
            // metamodel generation command 
            EMFMetamodelCommand(metamodelSupport=...)
        )
    }
    
    override fun run() = Unit
}
```

**Comment by ftomassetti** [comment]
Done
