### ISSUE TITLE
Point/Position naming

### ISSUE THREAD

**Issue by matozoid** [Strumenta/kolasu#12]
"Position" sounds like something that is in 1 place. In Kolasu it is more of a range from one point to another.

And of course, Point should be Position as it is in JavaParser :-)

**Comment by ftomassetti** [comment]
Another thing to consider, related to this is #27 
We should do this refactoring and understand if the name of the source (typically a source file) should go in "Point" -> "Position" or "Position" -> "Range"

**Comment by ftomassetti** [comment]
@mctaverna @alessiostalla @loradd do you have an opinion on the naming of these elements?

**Comment by mctaverna** [comment]
@ftomassetti  I don't really have an opinion, I remember that in GraalVM they have [SourceSection](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/source/SourceSection.html).

**Comment by alessiostalla** [comment]
Monaco/VSCode uses "range" for what we call Position. I wouldn't mind renaming Position to Range (and maybe Point to Position, though that could make migrating a bit confusing)

**Comment by ftomassetti** [comment]
Ok, then I think we converge on renaming Position to Range in Kolasu 1.6.
Regarding renaming Point to Position I agree it could make things confusing.
Would it make sense to keep Point so that we would have a Range being composed by two Points?
This would go in branch 1.6

**Comment by loradd** [comment]
> Ok, then I think we converge on renaming Position to Range in Kolasu 1.6. Regarding renaming Point to Position I agree it could make things confusing. Would it make sense to keep Point so that we would have a Range being composed by two Points? This would go in branch 1.6

Yes, I think that renaming `Position` to `Range` would be enough not to create too much confusion while achieving our goal.

**Comment by ftomassetti** [comment]
In branch `future/16` we completed the renaming
