### ISSUE TITLE
Serialization of AST's with ParseTreeOrigin doesn't work

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/kolasu#131]

**Comment by ftomassetti** [comment]
This is serialization to EMF-JSON, right? Not to native JSON or XML

I am not sure if this could work: I mean, should we aiming to replicate the whole parse-tree? On the other side they could not have the generated parse-tree classes to unserialize it anyway

**Comment by alessiostalla** [comment]
No, my idea is to ignore the parse tree origin and only save the position.
In any case, this should work (i.e. don't throw an exception) out of the
box.

Il ven 23 set 2022, 08:49 Federico Tomassetti ***@***.***> ha
scritto:
