### ISSUE TITLE
Publish dokka documentation online

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/kolasu#137]
We can already publish multimodule documentation using task `dokkaHtmlMultiModule`. We need to refine it and publish it.
Later we could link to it from https://starlasu.strumenta.com

**Comment by ftomassetti** [comment]
This article seems to be a good starting point: https://pgreze.dev/posts/2020-05-28-static-doc-netlify/

However, we may want to have multiple versions online at the same moment

**Comment by alessiostalla** [comment]
Kdocs are already being published here https://javadoc.io/doc/com.strumenta.kolasu it supports multiple versions already.

**Comment by ftomassetti** [comment]
We could also publish it in Dokka format, like here: https://6474918d12cf4169faa84282--kolasu.netlify.app/
However supporting more than one version would be complicated. Should we just drop this and use the javadoc format @alessiostalla ?

**Comment by alessiostalla** [comment]
I was not aware of that format! I have no idea about supporting multiple versions.

**Comment by ftomassetti** [comment]
For now, we can just use the javadoc.
