### ISSUE TITLE
Adding TokenType to KolasuToken

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/kolasu#174]
In the RPG Parser we are facing this error:
<img width="648" alt="Screenshot 2023-03-23 at 08 35 37" src="https://user-images.githubusercontent.com/439078/227134704-e1ab95f7-741e-4e86-91ee-5ed295510e2d.png">

This is because now the lex method returns a KolasuToken and not an ANTLR's Token.
The KolasuToken does not have a type.

I think it could be useful to have KolasuTokens having a field type of type TokenType. A TokenType could be identified by a name and belong to a TokenCategory. While the lexer would only need the TokenCategory, other applications could need to distinguish between different token types within the same category, so I think that having this distinction could be valuable.

What @alessiostalla and @gabriele-tomassetti think about this?

**Comment by alessiostalla** [comment]
What's the type of `AssignementParser` exactly? IMHO rather than introducing a TokenType concept we could simply use inheritance and generics to have the base lexer interface return basic tokens, while the ANTLR based implementation would return ANTLR tokens.
