### ISSUE TITLE
ParsingResult not serializable if firstStage is present

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/kolasu#190]
FirstStageParsingResult holds a reference to the ANTLR parse tree root which is not serializable.
I think we should make the entire first stage transient, because it mostly replicates some of the information in the ParsingResult. Or, alternatively, we could mark only `FirstStageParsingResult.root` as transient.

**Comment by ftomassetti** [comment]
If I understand correctly we have a workaround for this: setting the FirstStageParsingResult to null when looking to serialize a node. Is this correct?

**Comment by alessiostalla** [comment]
Yes. In fact I've done this, only to bump into the problem with Issue.
