### ISSUE TITLE
Collection usage

### ISSUE THREAD

**Issue by matozoid** [Strumenta/kolasu#20]
I see LinkedList and HashMap and such. Why not use the Kotlin collections?

**Comment by ftomassetti** [comment]
Because I thought that Kotlin used Java collections, should we use other collections?

**Comment by matozoid** [comment]
I only know what I read in the manual: https://kotlinlang.org/docs/reference/collections-overview.html so I tend to use mutableListOf() and friends.

**Comment by ftomassetti** [comment]
I think you solved this in #25
