### ISSUE TITLE
Concept inheritance doesn't work

### ISSUE THREAD

**Issue by AtanasM98** [Strumenta/kolasu#273]
I have a library language that has a "Writer" concept which gets extended into two other writer concepts. When I try to generate the AST.kt file I get the following errors on the class that tries to inherit from the superclass.
```
Function 'component1' generated for the data class conflicts with member of supertype 'Writer'
```
```
This type is final, so it cannot be inherited from
```
![image](https://github.com/Strumenta/kolasu/assets/89129481/c8e72f46-d3b2-4162-8b38-af46a0a2dbf8)

You can check out the project and file in [my repository.](https://github.com/f1re-nl/emf-gettingstarted/blob/632ce0b393ef2f336b17c0b89eb0f320326e3df9/nl.f1re.emf.library.kotlin/build/lionweb-gen/library/AST.kt)

**Comment by ftomassetti** [comment]
@AtanasM98 yes, by default classes are generated as data-classes, which cannot be extended. So we should check if a class is extended and if that is the case remove the data modifier.

As a workaround, you can simply define the class `Writer` in the same package (`library` in your repo). If you do that the lionweb class generator will notice and not try to generate the `Writer` class.

```
@LionWebAssociation(key = "library-Writer")
open class Writer(
  override var name: String,
) : Node(), Named
```

This worked for me:
<img width="1606" alt="Screenshot 2023-10-30 at 14 44 52" src="https://github.com/Strumenta/kolasu/assets/439078/30e79c94-3245-4be3-b0fe-70c7342aeb93">
