### ISSUE TITLE
Generate LionWeb chunk deserializers for Javascript/Typescript

### ISSUE THREAD

**Issue by martin-azpillaga** [Strumenta/kolasu#314]
When a client receives a tree serialized in LionWeb format, it must be deserialized back to classes to facilitate data manipulation.

This requires duplicating the language's data model in the client, creating all the classes and their relationships again.

Consider generating these data model classes and deserializers from an export of the Language from Kolasu, and the possible integrations with Tylasu.

**Comment by ftomassetti** [comment]
Yes, that should be done but in the StarLasu Tools. I will copy this issue there

**Comment by ftomassetti** [comment]
https://github.com/Strumenta/starlasu-tools/issues/102 has been created, closing this one
