### ISSUE TITLE
LionWebModelConverter nodes mapping

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/kolasu#318]
Sometimes `nodesMapping.byA` or `nodesMapping.byB` returns null even when the maps aren't shared across threads. It could be a problem in the application (how the AST is defined).

**Comment by ftomassetti** [comment]
I would need to investigate this, as I am not sure what could be causing that. I think these maps are based on identity, so it should not be a problem caused by hashcode or equals being depending on some values being changes between insertion and retrieval

**Comment by alessiostalla** [comment]
This was caused by the client being shared among threads, see https://github.com/Strumenta/starlasu-lionweb-repository-client/issues/22
