### ISSUE TITLE
Relax constraints for Kolasu parser instantiators

### ISSUE THREAD

**Issue by loradd** [Strumenta/kolasu#359]
When instantiating a parser, a corresponding instantiator is used at the moment. In order to implement a custom one, we can implement the `KolasuParserInstantiator` interface and bind it in our starlasu-conf.yaml file.

The current `KolasuParserInstantiator` can only be used with parsers extending `KolasuParser` and it would be nice to relax this constraint to `ASTParser`. For example, this would allow to use parser instantiators in the RPG parser project - where the main parser does not extend `KolasuParser`.

Using `ASTParser` instead of `KolasuParser` would still work as no methods or property specific of this last one is currently used. Indeed, we invoke the `parse` method on the instantiated parser and this method is inherited from `ASTParser`.

A possible solution to avoid breaking existing instantiators could consist in introducing an `ASTParserInstantiator` interface and make the `KolasuParserInstantiator` extend it.

Also see: https://github.com/Strumenta/starlasu-tools/issues/106

**Comment by loradd** [comment]
The `KolasuParserInstantiator` is currently only used in the `starlasu-tools`, I propose we move it there and fix this issue there.

**Comment by loradd** [comment]
I am currently working from the branch `maintenance/kolasu15`. Is this correct?

**Comment by ftomassetti** [comment]
> I am currently working from the branch maintenance/kolasu15. Is this correct? @ftomassetti

Yes, it is, thank you. We will then merge `maintenance/kolasu15` into `main`

**Comment by loradd** [comment]
Added comment explaining that `chiselDownloadExamples` is expected to be responsible for the download of the example projects.
