### ISSUE TITLE
Consider if we need to add marker interfaces (Statement, Expression, etc.) to StarLasuLWLanguage

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/kolasu#362]
We should write some tests exporting nodes with those interface to lionweb and then back.

Maybe we should create an example including nodes that refer to `Statement` and `Expression` directly.

```
data class MyNode(val e: Expression, val s: Statement): Node()
```

**Comment by alessiostalla** [comment]
Is this satisfied by the following test? https://github.com/Strumenta/kolasu/blob/07c9761fe358850b34a792304f96e533a5a54eea/lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverterTest.kt#L87

**Comment by ftomassetti** [comment]
Yes, I would say so.
I am closing the issue then.
