### ISSUE TITLE
ParseTree could be much simpler

### ISSUE THREAD

**Issue by asarkar** [Strumenta/kolasu#41]
[ParseTree](https://github.com/Strumenta/kolasu/blob/master/src/main/kotlin/com/strumenta/kolasu/parsing/ParseTree.kt) could be much simpler, see [here](https://github.com/asarkar/jsemver/blob/master/src/test/kotlin/com/asarkar/semver/antlr/ParseTree.kt)

**Comment by ftomassetti** [comment]
Thank you. We have since simplified ParseTree.
