### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/kolasu#46]
Improve documentation, ensure every class/method has KDoc comments attached.

**Comment by alessiostalla** [comment]
Not all classes are documented, I think. I left this open just to have a reference issue when someone documents something. 
I've done some research and there doesn't seem to be a ready-made documentation coverage plugin for Dokka. However, I found these pointers https://slack-chats.kotlinlang.org/t/2476007/hi-all-i-need-generate-coverage-for-inline-doc-at-my-code-an
Maybe we could build something like that ourselves.

IMHO we could close this issue and maybe open one about documentation coverage.

**Comment by ftomassetti** [comment]
I will do that, thank you
