### ISSUE TITLE
Ensure properties are not duplicated

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/kolasu#62]
There are cases in which we override properties and we end up with two properties definition.

In parser bench this is visible:
<img width="412" alt="Screenshot 2022-02-23 at 16 12 19" src="https://user-images.githubusercontent.com/439078/155347785-e86d4d10-fb92-4183-ba9a-99699f9a2792.png">

**Comment by alessiostalla** [comment]
I saw this in Parser Bench but forgot to open an issue. I _think_ this may be related only to the EMF export but I'm not sure.
