### ISSUE TITLE
The operation lambda for Node.transform can process same node more than once

### ISSUE THREAD

**Issue by arthur78** [Strumenta/kolasu#63]
https://github.com/Strumenta/kolasu/blob/d774ff6d8ef9d61af202e32367d2aa7f571a743b/core/src/main/kotlin/com/strumenta/kolasu/model/Processing.kt#L318

Please consider this test from the _Minicalc_ project:

```
    @test
    fun transformVarName() {
        val startTree = MiniCalcFile(listOf(
            VarDeclaration("A", IntLit("10")),
            Assignment(ReferenceByName("A"), IntLit("11")),
            Print(ValueReference(ReferenceByName("A")))))

        val expectedTransformedTree = MiniCalcFile(listOf(
            VarDeclaration("B", IntLit("10")),
            Assignment(ReferenceByName("B"), IntLit("11")),
            Print(ValueReference(ReferenceByName("B")))))

        assertEquals(expectedTransformedTree, startTree.transform {
            println("Hashcode: ${it.hashCode()}")
            when (it) {
                is VarDeclaration -> VarDeclaration("B", it.value)
                is ValueReference -> ValueReference(ReferenceByName("B"))
                is Assignment -> Assignment(ReferenceByName("B"), it.value)
                else -> it
            }
        })
    }
```

Note the `println("Hashcode: ${it.hashCode()}")` line that I added.

This is what's being printed if we run this test with the original implementation of the _Node.transform_ function:

- Hashcode: 1422860865
- Hashcode: 1568352
- Hashcode: 48577
- Hashcode: 48577
- Hashcode: 1568352
- Hashcode: 2006568
- Hashcode: 48608
- Hashcode: 48608
- Hashcode: 2006568
- Hashcode: 499720
- Hashcode: 16120
- Hashcode: 16120
- Hashcode: 507408
- Hashcode: 1459116512

As you can see, some of the nodes are processed twice.

Now please see what's printed in the case I comment out the `operation(this)` at https://github.com/Strumenta/kolasu/blob/master/core/src/main/kotlin/com/strumenta/kolasu/model/Processing.kt#L318:

- Hashcode: 48577
- Hashcode: 1568352
- Hashcode: 48608
- Hashcode: 2006568
- Hashcode: 16120
- Hashcode: 507408
- Hashcode: 1459116512

We don't see duplicates anymore, however, the test passes in either case. 

P.S. I first noticed this behavior in the 0.1.1 version. I tried to use the newest version but it seemed to behave similarly.

**Comment by ftomassetti** [comment]
Thank you for reporting this. I just merged a fix that should be available in next release (1.4.2)
