### ISSUE TITLE
Allow overriding node.position independently of origin

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/kolasu#81]
It was a design mistake to couple position and origin. A node has an origin with a position but its actual position could be different. This happens e.g. when a new node is inserted in an existing tree.

**Comment by ftomassetti** [comment]
Currently in master I have done this change:

```
class ParseTreeOrigin(val parseTree: ParseTree) : Origin {
    private var overriddenPosition: Position? = null

    fun overridePosition(overriddenPosition: Position) {
        this.overriddenPosition = overriddenPosition
    }

    override val position: Position?
        get() = overriddenPosition ?: parseTree.toPosition()

    override val sourceText: String?
        get() =
            when (parseTree) {
                is ParserRuleContext -> {
                    parseTree.getOriginalText()
                }
                is TerminalNode -> {
                    parseTree.text
                }
                else -> null
            }
}
```

Should we instead have the position not coming from Origin? Maybe we could have Origin provides an optional position which could be overridden directly in the Node

**Comment by alessiostalla** [comment]
Yes I think Origin should have a position, but Node ought to be able to override it. I would move the overriddenPosition to Node (and get rid of the JustPosition origin)

**Comment by ftomassetti** [comment]
I think your solution would make sense, yes
