### ISSUE TITLE
Introduce markers for common elements (e.g., statement, expression, entity declaration)

### ISSUE THREAD

**Issue by ftomassetti** [Strumenta/kolasu#86]
If we were able to know which nodes represents statements and expressions, we could have generic logic to print stats, maybe generate sequence diagrams and perform analysis

**Comment by mctaverna** [comment]
The sequence diagram generation  implemented for Source@Max is a simple transpiler from VB to PUML.
I have hardcoded the logic for the AST processing and code generation and a global symbol table to resolve the function/procedure name across the different modules. 
Not sure how simple it is for a generic language, for sure it is required to provide the list of nodes that must be considered an invocation.

**Comment by ftomassetti** [comment]
Right, I did not consider the resolution part. Maybe the sequence diagrams are beyond the scope of Kolasu and to be implemented in specific parsers

**Comment by ftomassetti** [comment]
Closed via #95
